### ISSUE TITLE
Unable to Locate "hindi-train.csv" File.

### ISSUE THREAD

**Issue by SutanshuRaj** [goru001/nlp-for-hindi#1]
Hi Gaurav,

Great initiative on vernacular languages. I had a small doubt, and was hoping you could clarify it for me. While trying to replicate some of your codes in the repository, I noticed that in the `Hindi_Classification_Model-BBC_Hindi_News_Data.ipynb` notebook, you import a `hindi-train.csv` file (in **cell [5]**). Unfortunately, I wasn't able to locate that file. Could you guide me in the right direction?

**Comment by goru001** [comment]
Thanks for reaching out! The BBC News hindi dataset was prepared by @NirantK . I've provided a link to it in the readme. You can[ check it out here](https://github.com/NirantK/hindi2vec/releases/tag/bbc-hindi-v0.1)

**Comment by goru001** [comment]
I'll close this issue! Feel free to reopen if there's anything!
