### ISSUE TITLE
unable to access the pretrained model third_hi_lm.pth.zip 

### ISSUE THREAD

**Issue by rashmiofficial** [goru001/nlp-for-hindi#2]
unable to open the pre-trained model for this project where is used curl to download it directly and also unzipped it there but then the file couldn't be accessed by the download link being specified. Is there any other model i can access or maybe access this from some other link. Any help please!

**Comment by goru001** [comment]
@rashmiofficial Sorry for the late reply. I missed this issue. Ideally there shouldn't be any issue with downloading models from Dropbox. 
Having said that, I've just updated the links to models (adding the TransformerXL model as well). Let me know if you face any issues moving forward.
I'll close this issue, feel free to open if you face any issues.
