### ISSUE TITLE
ULMFit Model issues

### ISSUE THREAD

**Issue by dipamgoswami** [goru001/nlp-for-hindi#3]
In the Jupyter [Notebook](https://github.com/goru001/nlp-for-hindi/blob/master/language-model/Hindi_Language_Model_ULMFiT_172k.ipynb), I am unable to understand a few things:
1. What does the path/'hindi_transformer' refer to? Is it referring to the Training Corpus? Also, Is it required to have separate training and validation corpus?
In [19]:
data_lm = TextLMDataBunch.from_folder(path=path/'hindi_transformer', tokenizer=tokenizer, vocab=hindi_vocab)

2. In the Class HindiTokenizer, what does the path - (path/"../tokenizer/hindi_lm_large.model") refer to? What language model is it referring to?

Any help would be appreciated. Thanks!

**Comment by goru001** [comment]
Hi @dipamgoswami , thanks for reaching out! I missed notification for this! 

1. `path/'hindi_transformer'` is the path on my local system, and yes you should have `train` and `valid` corpus. You can download the datasets used if you want, from the links provided in README.

2. `path/"../tokenizer/hindi_lm_large.model"` - this is the path to tokenizer model trained using sentencepiece. You can download this model from the links provided in README.

**Comment by goru001** [comment]
Closing this issue for now, feel free to reopen if there's anything else.
